apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: default
type: Opaque
stringData:
  mysql_url: "jdbc:mysql://db-service.petclinic.svc.cluster.local:3306/petclinic"
  mysql_pw : "petclinic"
